2019-02-20 17:52:32,955 - com-mqtt - CRITICAL - device reports readiness to read but returned no data (device disconnected or multiple access on port?)
Traceback (most recent call last):
  File "mqtt-frwd.py", line 146, in <module>
    main(sys.argv)
  File "mqtt-frwd.py", line 130, in main
    main_loop(TOPIC_START, client, ser)
  File "mqtt-frwd.py", line 84, in main_loop
    line, result = read_line_serial(ser)
  File "mqtt-frwd.py", line 31, in read_line_serial
    if ser.read() == ':':
  File "/home/vovva/.local/lib/python2.7/site-packages/serial/serialposix.py", line 501, in read
    'device reports readiness to read but returned no data '
SerialException: device reports readiness to read but returned no data (device disconnected or multiple access on port?)
2019-02-20 17:53:23,898 - com-mqtt - CRITICAL - device reports readiness to read but returned no data (device disconnected or multiple access on port?)
Traceback (most recent call last):
  File "mqtt-frwd.py", line 146, in <module>
    main(sys.argv)
  File "mqtt-frwd.py", line 130, in main
    main_loop(TOPIC_START, client, ser)
  File "mqtt-frwd.py", line 84, in main_loop
    line, result = read_line_serial(ser)
  File "mqtt-frwd.py", line 31, in read_line_serial
    if ser.read() == ':':
  File "/home/vovva/.local/lib/python2.7/site-packages/serial/serialposix.py", line 501, in read
    'device reports readiness to read but returned no data '
SerialException: device reports readiness to read but returned no data (device disconnected or multiple access on port?)
2019-02-20 17:57:02,582 - com-mqtt - CRITICAL - device reports readiness to read but returned no data (device disconnected or multiple access on port?)
Traceback (most recent call last):
  File "mqtt-frwd.py", line 146, in <module>
    main(sys.argv)
  File "mqtt-frwd.py", line 130, in main
    main_loop(TOPIC_START, client, ser)
  File "mqtt-frwd.py", line 84, in main_loop
    line, result = read_line_serial(ser)
  File "mqtt-frwd.py", line 38, in read_line_serial
    l = ser.read()
  File "/home/vovva/.local/lib/python2.7/site-packages/serial/serialposix.py", line 501, in read
    'device reports readiness to read but returned no data '
SerialException: device reports readiness to read but returned no data (device disconnected or multiple access on port?)
